#!/bin/bash

#SURFACE=HD-airframe-aileron-gap-rear-edge 
SURFACE=littleboxoffset

# CG aft of datum (for torque calculations)
CG_INCHES=-10

# output into this directory
ODIR=run-`date "+%Y%m%d-%H%M%S"`-$SURFACE

# convert to meters and relative to input datum
DATUM_M=-0.385
X_ORIGIN=$(bc -l <<< "$DATUM_M+$CG_INCHES*0.0254")


echo -n "Starting calculation on "; date

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# create output directory structure
mkdir -p outputs/$ODIR/constant/polyMesh
mkdir outputs/$ODIR/constant/triSurface
mkdir outputs/$ODIR/system

# copy all inputs to be able to reproduce the calculation later
mkdir outputs/$ODIR/reproduce
cp -r $0 wind clean inmemory inputs 0.orig outputs/$ODIR/reproduce/

# copy input files into their directories
cp inputs/blockMeshDict       outputs/$ODIR/constant/polyMesh/
cp inputs/transportProperties outputs/$ODIR/constant/
cp inputs/RASProperties       outputs/$ODIR/constant/
cp inputs/controlDict         outputs/$ODIR/system/
cp inputs/forces              outputs/$ODIR/system/
cp inputs/fvSchemes           outputs/$ODIR/system/
cp inputs/fvSolution          outputs/$ODIR/system/
cp inputs/surfaceFeatureExtractDict outputs/$ODIR/system/
cp inputs/snappyHexMeshDict   outputs/$ODIR/system/

# copy the surface to test 
cp ../constant/triSurface/$SURFACE.stl outputs/$ODIR/constant/triSurface/

# everything in place, commence computations
cd outputs/$ODIR

# scale the surface from millimeters to meters
surfaceTransformPoints -scale '(0.016 0.016 0.016)' \
  constant/triSurface/$SURFACE.stl \
  constant/triSurface/testsurface_meters.stl > log.scale 2>&1

# translate so the datum (wing root leading edge) is at (0, 0, 0)
surfaceTransformPoints -translate "($X_ORIGIN 0 -0.060)" \
  constant/triSurface/testsurface_meters.stl \
  constant/triSurface/testsurface_datum.stl > log.translate 2>&1

# rotate surface to the desired roll, pitch and yaw (3deg nominal incidence of the HD wing)
surfaceTransformPoints -rollPitchYaw "(0 3 0)" \
  constant/triSurface/testsurface_datum.stl \
  constant/triSurface/testsurface.stl > log.rotate 2>&1

# create the wind tunnel
runApplication blockMesh

# find out where the action is
runApplication surfaceFeatureExtract 

# mesh the volume
runApplication snappyHexMesh -overwrite

refineWallLayer -overwrite testsurface 0.3 > log.boundary 2>&1
refineWallLayer -overwrite testsurface 0.3 >> log.boundary 2>&1


# copy initial conditions
cp -r ../../0.orig 0.orig

echo -n "Ending calculation at "; date

paraFoam&
sleep 1
